# Generated by Django 3.0.1 on 2019-12-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_img_id', models.CharField(blank=True, default='NA', max_length=255)),
                ('ans_arr', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_img', models.ImageField(blank='NULL', default='NULL', max_length=255, upload_to='p_image')),
                ('p_img_count', models.IntegerField(default=0)),
                ('s_image1', models.ImageField(max_length=255, upload_to='s_image')),
                ('s_image2', models.ImageField(blank='NULL', default='NULL', max_length=255, upload_to='s_image')),
                ('s_image3', models.ImageField(blank='NULL', default='NULL', max_length=255, upload_to='s_image')),
                ('s_image4', models.ImageField(blank='NULL', default='NULL', max_length=255, upload_to='s_image')),
                ('s_image5', models.ImageField(blank='NULL', default='NULL', max_length=255, upload_to='s_image')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='NA', max_length=255)),
                ('p_img_id', models.IntegerField()),
                ('p_ans', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='NA', max_length=255)),
                ('p_img_id', models.IntegerField()),
            ],
        ),
    ]
