# Generated by Django 3.0.1 on 2019-12-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_image', models.ImageField(default='', upload_to='media/p_image')),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
