# Generated by Django 3.0.1 on 2019-12-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0002_auto_20191221_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='s_image1',
            field=models.ImageField(default='NA', max_length=255, upload_to='s_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='s_image2',
            field=models.ImageField(blank='NULL', default='NULL', max_length=255, upload_to='s_image'),
        ),
        migrations.AddField(
            model_name='image',
            name='s_image3',
            field=models.ImageField(blank='NULL', default='NULL', max_length=255, upload_to='s_image'),
        ),
        migrations.AddField(
            model_name='image',
            name='s_image4',
            field=models.ImageField(blank='NULL', default='NULL', max_length=255, upload_to='s_image'),
        ),
        migrations.AddField(
            model_name='image',
            name='s_image5',
            field=models.ImageField(blank='NULL', default='NULL', max_length=255, upload_to='s_image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='p_image',
            field=models.ImageField(blank='NULL', default='NULL', max_length=255, upload_to='p_image'),
        ),
    ]
