# Generated by Django 3.0.1 on 2019-12-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0006_auto_20191222_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='s_image1',
            field=models.ImageField(max_length=255, upload_to='s_image'),
        ),
    ]
