# Generated by Django 2.1.9 on 2019-12-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0007_auto_20191223_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='p_image_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='s_image1_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='s_image2_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='s_image3_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='s_image4_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='s_image5_flag',
            field=models.BooleanField(default=False),
        ),
    ]
