# Generated by Django 3.0.1 on 2019-12-23 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pair', '0008_auto_20191223_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='s_image1_flag',
        ),
        migrations.RemoveField(
            model_name='image',
            name='s_image2_flag',
        ),
        migrations.RemoveField(
            model_name='image',
            name='s_image3_flag',
        ),
        migrations.RemoveField(
            model_name='image',
            name='s_image4_flag',
        ),
        migrations.RemoveField(
            model_name='image',
            name='s_image5_flag',
        ),
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
