# Generated by Django 3.0.1 on 2019-12-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0009_auto_20191223_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='p_image',
            new_name='p_img',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='p_image_count',
            new_name='p_img_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.AddField(
            model_name='answers',
            name='ans_arr',
            field=models.CharField(default='NULL', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='a1',
            field=models.CharField(blank='NULL', default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='a10',
            field=models.CharField(blank='NULL', default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='a11',
            field=models.CharField(blank='NULL', default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='a12',
            field=models.CharField(blank='NULL', default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='a13',
            field=models.CharField(blank='NULL', default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='a14',
            field=models.CharField(blank='NULL', default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='a15',
            field=models.CharField(blank='NULL', default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='a2',
            field=models.CharField(blank='NULL', default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='a3',
            field=models.CharField(blank='NULL', default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='a4',
            field=models.CharField(blank='NULL', default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='a5',
            field=models.CharField(blank='NULL', default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='a6',
            field=models.CharField(blank='NULL', default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='a7',
            field=models.CharField(blank='NULL', default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='a8',
            field=models.CharField(blank='NULL', default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='a9',
            field=models.CharField(blank='NULL', default='NULL', max_length=255),
        ),
    ]
