# Generated by Django 3.0.1 on 2019-12-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0010_auto_20191224_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='a1',
            new_name='0',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='a10',
            new_name='1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='a11',
            new_name='10',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='a12',
            new_name='11',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='a13',
            new_name='12',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='a14',
            new_name='13',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='a15',
            new_name='14',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='a2',
            new_name='2',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='a3',
            new_name='3',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='a4',
            new_name='4',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='a5',
            new_name='5',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='a6',
            new_name='6',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='a7',
            new_name='7',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='a8',
            new_name='8',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='a9',
            new_name='9',
        ),
    ]
