# Generated by Django 3.0.1 on 2019-12-24 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pair', '0012_auto_20191224_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='a0',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='a1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='a10',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='a11',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='a12',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='a13',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='a14',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='a2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='a3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='a4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='a5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='a6',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='a7',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='a8',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='a9',
        ),
        migrations.AddField(
            model_name='profile',
            name='p_ans',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='p_img_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
