# Generated by Django 3.0.1 on 2019-12-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0013_auto_20191224_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
